### ISSUE TITLE
catch-all route rending index.html not working

### ISSUE THREAD

**Issue by dougkna** [fractalliter/express-react-typescript#16]
`// Send index.html on root request
app.use(express.static('dist'));
app.get('/*', (req: Request, res: Response) => { //<---- change to '/*'
    console.log('sending index.html');
    res.sendFile('/dist/index.html');
});`

in production refreshing any page route (i.e. site.com/page1) will not make express server serve index.html?

```const outputPath = path.resolve(process.cwd(), 'dist');
app.use('/', express.static(outputPath));

app.get('/*', (req, res) => {
  console.log('sending index.html');
  res.sendFile(path.resolve(outputPath, 'index.html'), err => {
    if (err) {
      res.sendStatus(404);
    }
  })
});

**Comment by fractalliter** [comment]
Could you please provide more information about the environment that you are deploying? OS, Web server and so on.

**Comment by fractalliter** [comment]
Due to inactivity
